import pickle
import streamlit as st

from halcyon.generative import AutoGeneratedScorer

st.title("Demo Scoring App")

# Load the model from disk
with open("models/autogen.pkl", "rb") as f:
    model = pickle.load(f)

# Init the autogen scorer
scorer = AutoGeneratedScorer(model)

# Get user input
text = st.text_area("Enter some text")
button = st.button("Score")

# Score the text
if button:
    scores = scorer.score(text)
    st.write(scores)
